### ISSUE TITLE
Auditd D Support for AMA agent

### ISSUE THREAD

**Issue by jr488m** [Azure/aks-auditd#1]
With the deprecation of the OMS Agent is there any plans to update this image or create another image that support the AMA agent instead of the OMS Agent?

**Comment by KiPIDesTAN** [comment]
I wrote an updated version [here](https://github.com/KiPIDesTAN/aks-auditd). It uses the new Container Insights syslog capabilities. 

There is an end to end Terraform demo, including how to monitor the daemonset, in the [demo](https://github.com/KiPIDesTAN/aks-auditd/tree/main/demo) folder.

**Comment by jr488m** [comment]
Awesome, Thank you.
